### ISSUE TITLE
組込み手続きxmp_scatterの動作

### ISSUE THREAD

**Issue by mnakao** [XcalableMP/Specification#12]
報告者: 村井

`x(idx(:)) = a(:)`
という代入文に相当する

`call xmp_scatter(x, a, idx)`

において、idx の値に重複がある場合(x のある要素が複数回更新される場合)の扱いが定義されていない。「結果は不定」とするべきか。

なお、Fortranでは、そのような代入文は許されない(shall not appear)ことになっている。

**Comment by h-murai** [comment]
「結果は不定」とする。
