### ISSUE TITLE
マイナスのリダクション

### ISSUE THREAD

**Issue by mnakao** [XcalableMP/Specification#13]
報告者：村井

XMP に置けるリダクションのセマンティクスの下では「-」のリダクションの動作を定義しづらく、また「-」のリダクションは「+」のリダクションで置き換えることが比較的容易であるため、仕様から削除することを提案する。

**Comment by mnakao** [comment]
報告者：村井

アプリ的には，電子の電流を計算する場合，電荷が負なので，

```
ecur = 0
do i = ...
   ecur = ecur - ve(i)
end do
```

と書くのが素直です．なので積極的に削除するのは，どうでしょうか？
動作の定義は，「+」を「-」に読み替えるだけでいいと思いますが，どういうふうに難しいのですか？

**Comment by h-murai** [comment]
- loop指示文のreduction節では「-」をアリとした上で、その実際の動作を、「+」のreduction指示文として定義する。
- reduction指示文の「-」は削除する。

ある意味で、reduction節の「-」はsyntactic sugarとして残す、という扱い。

**Comment by mnakao** [comment]
マイナスのリダクションは意味がないので、仕様書には定義しない。
