### ISSUE TITLE
不規則問題向け機能の検討

### ISSUE THREAD

**Issue by mnakao** [XcalableMP/Specification#2]
報告者: 村井

ハローの言語仕様を提案。

HPF/SX のハロー機能から以下の点を変更。
- ハローを参照する可能性がある(＝特別なアドレス変換が必要になる)ことを示す halo 節 ⇔ local 節
- ハローに対するリダクション操作を指示する halo_reduction 節/指示文  ⇔ reduction 節の local 修飾子

[halo2.pptx](https://github.com/XcalableMP/Specification/files/273920/halo2.pptx)

**Comment by mnakao** [comment]
報告者：岩下

まずどういうモデルの実現を目指すのか意識合わせしたい。
検討のための図を添付します。

[halo関連のいろいろ.pptx](https://github.com/XcalableMP/Specification/files/273924/halo.pptx)

**Comment by h-murai** [comment]
部会での検討の結果、クローズ。
