### ISSUE TITLE
メモリ一貫性モデルに関する記述をappendixで行う

### ISSUE THREAD

**Issue by abetatsuya** [XcalableMP/Specification#48]
XcalableMPのメモリ一貫性モデルに関する記述をappendixで行う件です。

目的：
1. XcalableMPがメモリ一貫性モデルを無視していないことを、メモリ一貫性モデルという術語を目次に現れるようにすることで明確にする。
2. 一般に、メモリ操作に関するあらゆることに影響があるため、仕様全体に散らばりがちなメモリ一貫性モデルに関する記述を一つにまとめる。

記述ポリシー：
1. 仕様メモリ一貫性モデルに影響するものから、XcalableMPのメモリ一貫性モデルの原理・原則を抽出する。
2. 1に関連することであるが、appendixの記述を理由に仕様に対する制限・変更を要求しない。整合しないところがあれば指摘をすることで仕様策定へフィードバックをすることはあるかもしれない。

現況：
1. 仕様バージョン1.3以降にappendixに追加したが、次期バージョンが1.4でなく2.0になる予定なのでこのタイミングで規格部会の承認を得て追加したい。
2. 2015年3月5日(木)の規格部会で一度紹介を行った。
3. サンプルプログラムを作成し、仕様から抽出した原理の下では保証できないメモリへの書き込み等に関する記述を行っている。これに関する個別の反応は得られていないため、おそらく正しさを確認したのが作成した安部自身だけであるという問題がある。

既にappendixに存在する他の章と同様の手続きですすめたい。

**Comment by abetatsuya** [comment]
2016年8月19日の規格部会で提案を行った。次回の規格部会（2016年9月29日予定）で承認を議題に挙げる。

**Comment by hidetoshi-iwashita** [comment]
1.3は公開されていないようです．
http://xcalablemp.org/specification.html
http://xcalablemp.org/ja/specification.html
安倍さんの最新版はどこから参照すればよいですか？

**Comment by abetatsuya** [comment]
>1.3$B$O8x3+$5$l$F$$$J$$$h$&$G$9!%(B
$B$=$&$J$s$G$9$M!#(B

$B$G$O!"(B
https://github.com/XcalableMP/Specification
$B$r(B git clone$B!J0JA0$K$7$F$$$k$J$i(B git pull $B$G:G?7$K!K(B $B$7$F(B make $B$9$k$H(B
Appendix E $B$K(B Memory Consistency Model$B$N>O$,$G$-$^$9$N$G$=$l$G3NG'$7$F(B
$B$/$@$5$$!#(B

**Comment by abetatsuya** [comment]
> 1.3は公開されていないようです．
> そうなんですね。

では、
https://github.com/XcalableMP/Specification
を git clone（以前にしているなら git pull で最新に） して make すると
Appendix E に Memory Consistency Modelの章ができますのでそれで確認して
ください。

**Comment by abetatsuya** [comment]
> 1. 仕様バージョン1.3以降にappendixに追加したが、
>    「1.2.1から1.3にバージョンアップするにあたってのリポジトリにある1.2.1からのドラフト版のappendixに追加したが、」
>    と書いておくべきでした。

**Comment by abetatsuya** [comment]
2016年10月12日に岩下さんと対面で打合せを行い、Appendix E のレビューしてもらい、記述とプログラム例のバグフィクスを行いました。

**Comment by abetatsuya** [comment]
2017年1月12日の規格部会で承認多数で承認され、appendixに既に記載されていたものを以て次回リリースのappendixに採用されることになった。
